# -*- coding: utf-8 -*-
"""HW3_skeleton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/josedavp/data_science/blob/main/hw3/HW3_skeleton.ipynb

# HW3 code skeleton

Code for Q1-Q7.

#### % import necessary modules
"""
# %%


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt
from numpy import diag
import scipy.stats

"""#### % load the data and setup some variables

data is a numpy ndarray of shape (3,41,12) for the three diseases, 41 years and 12 months
"""
# %%


diseases = ['Measles', 'Mumps', 'ChickenPox']
year = np.arange(1931, 1972)
month = np.arange(1, 13)
month_str = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')


url = 'diseases.csv'
# uncomment the following to read directly from github
url = 'https://raw.githubusercontent.com/jianhuaruan/3753/main/' + url
data = pd.read_csv(url,header=None).values
data = data.reshape([3, 41, 12]) #data[0], data[1], and data[2] is for measles, mumps, and chickenpox
# %%


"""### % Q1 calucate and show mean number of cases per year, and 95% CI of the mean"""

m = data
#mSEM = np.std(m)/sqrt(len(m[0])) # SEM = std / sqrt(n)
msum=  np.sum(m[0], 1)
mmean= np.mean(msum)
mSTD = np.std(msum)

musum= np.sum(m[1],1)
mumean=  np.mean(musum)
muSTD = np.std(musum) # SEM = std / sqrt(n)

chPsum= np.sum(m[2],1)
chPmean= np.mean(chPsum)
chPSTD = np.std(chPsum) # SEM = std / sqrt(n)

measlesCI = (mSTD/sqrt(len(m[0]))) * 1.96 # SEM = std / sqrt(n)
mumpsCI = (muSTD/sqrt(len(m[1]))) * 1.96 # SEM = std / sqrt(n)
chPCI = (chPSTD/sqrt(len(m[2]))) * 1.96 # SEM = std / sqrt(n)
arrCI = np.array([measlesCI,mumpsCI, chPCI])
arrMean = np.array([mmean, mumean, chPmean])

plt.errorbar([1,2,3],arrMean, arrCI, marker='d', linestyle='', capsize=5)
plt.xticks([1,2,3], ['measles', 'mumps', 'chickenpox'])
plt.ylim([0, 25000])
plt.xlabel('NYC Diseases')
plt.ylabel('Number of cases')
plt.title('Fig 1: # of disease cases per year (mean & 95% CI)')
plt.show()
# %%


"""### % Q2 calculate and show percent of cases occurred in each month

"""
mCase = (sum(data[0])/sum(sum(data[0]))) * 100
muCase = (sum(data[1]) / sum(sum(data[1]))) * 100
chPCase = (sum(data[2]) / sum(sum(data[2]))) * 100
arrCases = np.array([mCase, muCase, chPCase])
plt.figure()
plt.plot(arrCases[0])
plt.plot(arrCases[1])
plt.plot(arrCases[2])
#plt.plot(arrCases[1])
#plt.plot(arrCases[2])
#plt.xticks([1,2,3])
plt.xlim(0, 12, 2)
#plt.ylim(0, 25)
plt.xlabel('Month')
plt.ylabel('Percent of cases')
plt.legend(diseases)
plt.title('Fig 2: Percent of cases in each month')
plt.show()
# %%


"""### % Q3 Scatter plot and correlation, mean monthly cases of Measles vs mumps"""

# Q3.1 scatter plot
ind1 = 0
ind2 = 1
mMean = np.mean(data[0], 0)
muMean = np.mean(data[1], 0)


# Q3.2 Pearson correlation
pearsonCal = scipy.stats.pearsonr(mMean, muMean)

# Q3.2 Spearman correlation coefficient
spearmanCal = scipy.stats.spearmanr(mMean,muMean)

plt.figure()
plt.xlabel('Mean monthly cases of Measles')
plt.ylabel('Mean monthly cases of Mumps')
plt.scatter(mMean, muMean)
plt.legend(pearsonCal, spearmanCal)
plt.xlim(0, 4000, 500)
plt.title('Fig 3: Mean monthly cases of %s vs %s' % (diseases[ind1], diseases[ind2]))
plt.show()

print('Pearson corr: %.4f' % 0)
print('Spearman corr: %.4f' % 0)
# %%


"""### % Q4 Scatter plot and correlation, annual cases of measles vs mumps"""

# 4.1 scatter plot

ind1 = 0
ind2 = 1
mSum = np.sum(data[0], 1)
muSum = np.sum(data[1], 1)
plt.figure()
plt.xlabel('Annual cases of Measles')
plt.ylabel('Annual cases of Mumps')
plt.scatter(mSum, muSum)
plt.xlim(0,80000, 10000)
plt.title('Fig 4: Annual cases of %s vs %s' % (diseases[ind1], diseases[ind2]))

# 4.2 Pearson correlation coefficient
pearsonCal1 = scipy.stats.pearsonr(mSum, muSum)

# 4.3 Spearman correlation
spearmanCal1 = scipy.stats.spearmanr(mSum, muSum)
plt.legend(pearsonCal1, spearmanCal1)
plt.show()

print('Pearson correlation: %.4f' % 0)
print('Spearman correlation: %.4f ' % 0)
# %%


"""### % Q5 Scatter plot and correlation, monthly cases of Measles vs mumps"""

# 5.1 scatter plot and correlation in original space


plt.figure()

ind1 = 0
ind2 = 1
mSum1 = np.sum(data[0], 1)
muSum1 = np.sum(data[1], 1)

plt.xlabel('Monthly cases of Measles')
plt.ylabel('Monthly cases of Mumps')
plt.scatter(mSum1, muSum1)
plt.xlim(0,25000, 5000)
plt.title('Fig 5.1: Monthly cases of %s vs %s' % (diseases[ind1], diseases[ind2]))

# Pearson correlation coefficient

# Spearman correlation between annual cases of mumps vs chicken pox


plt.show()

print('Pearson correlation in orignal space: %.4f' % 0)
print('Spearman correlation in original space: %.4f ' % 0)
# %%
# 5.2 scatter plot and correlation in log space

plt.figure()

ind1 = 0
ind2 = 1

plt.title('Fig 5.2: Monthly cases of %s vs %s' % (diseases[ind1], diseases[ind2]))

# Pearson correlation coefficient

# Spearman correlation

plt.show()

print('Pearson correlation in log space: %.4f' % 0)
print('Spearman correlation in log space: %.4f ' % 0)
# %%


"""### % Q6 (bonus) Correlation between number of mumps cases in different months"""

# %%


"""###% Q7 (Bonus) calculate and show average perecent of diseases occurred in each month"""






