# -*- coding: utf-8 -*-
"""HW3_skeleton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/josedavp/data_science/blob/main/hw3/HW3_skeleton.ipynb

# HW3 code skeleton

Code for Q1-Q7.

#### % import necessary modules
"""
# %%


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt
from numpy import diag
import scipy.stats

"""#### % load the data and setup some variables

data is a numpy ndarray of shape (3,41,12) for the three diseases, 41 years and 12 months
"""
# %%


diseases = ['Measles', 'Mumps', 'ChickenPox']
year = np.arange(1931, 1972)
month = np.arange(1, 13)
month_str = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')


url = 'diseases.csv'
# uncomment the following to read directly from github
url = 'https://raw.githubusercontent.com/jianhuaruan/3753/main/' + url
data = pd.read_csv(url,header=None).values
data = data.reshape([3, 41, 12]) #data[0], data[1], and data[2] is for measles, mumps, and chickenpox
# %%


"""### % Q1 calucate and show mean number of cases per year, and 95% CI of the mean"""

m = data
#mSEM = np.std(m)/sqrt(len(m[0])) # SEM = std / sqrt(n)
msum=  np.sum(m[0], 1)
mmean= np.mean(msum)
mSTD = np.std(msum)

musum= np.sum(m[1],1)
mumean=  np.mean(musum)
muSTD = np.std(musum) # SEM = std / sqrt(n)

chPsum= np.sum(m[2],1)
chPmean= np.mean(chPsum)
chPSTD = np.std(chPsum) # SEM = std / sqrt(n)

measlesCI = (mSTD/sqrt(len(m[0]))) * 1.96 # SEM = std / sqrt(n)
mumpsCI = (muSTD/sqrt(len(m[1]))) * 1.96 # SEM = std / sqrt(n)
chPCI = (chPSTD/sqrt(len(m[2]))) * 1.96 # SEM = std / sqrt(n)
arrCI = np.array([measlesCI,mumpsCI, chPCI])
arrMean = np.array([mmean, mumean, chPmean])

plt.errorbar([1,2,3],arrMean, arrCI, marker='d', linestyle='', capsize=5)
plt.xticks([1,2,3], ['measles', 'mumps', 'chickenpox'])
plt.ylim([0, 25000])
plt.xlabel('NYC Diseases')
plt.ylabel('Number of cases')
plt.title('Fig 1: # of disease cases per year (mean & 95% CI)')
plt.show()
# %%


"""### % Q2 calucate and show percent of cases occurred in each month

"""

plt.figure()

plt.title('Fig 2: Percent of cases in each month')
plt.show()
# %%
